import type { Config } from "tailwindcss";

// Material 3 role tokens live in src/index.css as CSS variables (generated by
// scripts/gen-m3-tokens.mjs). This config only mirrors them so utilities like
// `bg-surface` / `text-primary` / `rounded-md3-lg` exist. Do not add colors
// that are not M3 roles.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--md-primary)",
        "on-primary": "var(--md-on-primary)",
        "primary-container": "var(--md-primary-container)",
        "on-primary-container": "var(--md-on-primary-container)",
        secondary: "var(--md-secondary)",
        "on-secondary": "var(--md-on-secondary)",
        "secondary-container": "var(--md-secondary-container)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        tertiary: "var(--md-tertiary)",
        "on-tertiary": "var(--md-on-tertiary)",
        "tertiary-container": "var(--md-tertiary-container)",
        "on-tertiary-container": "var(--md-on-tertiary-container)",
        error: "var(--md-error)",
        "on-error": "var(--md-on-error)",
        "error-container": "var(--md-error-container)",
        "on-error-container": "var(--md-on-error-container)",
        success: "var(--md-success)",
        "on-success": "var(--md-on-success)",
        "success-container": "var(--md-success-container)",
        "on-success-container": "var(--md-on-success-container)",
        warning: "var(--md-warning)",
        "on-warning": "var(--md-on-warning)",
        "warning-container": "var(--md-warning-container)",
        "on-warning-container": "var(--md-on-warning-container)",
        surface: "var(--md-surface)",
        "surface-dim": "var(--md-surface-dim)",
        "surface-bright": "var(--md-surface-bright)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "surface-container-low": "var(--md-surface-container-low)",
        "surface-container": "var(--md-surface-container)",
        "surface-container-high": "var(--md-surface-container-high)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "surface-variant": "var(--md-surface-variant)",
        "on-surface": "var(--md-on-surface)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        outline: "var(--md-outline)",
        "outline-variant": "var(--md-outline-variant)",
        "inverse-surface": "var(--md-inverse-surface)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        "inverse-primary": "var(--md-inverse-primary)",
        scrim: "var(--md-scrim)",
      },
      fontFamily: {
        sans: ["Roboto", "'Helvetica Neue'", "Arial", "system-ui", "sans-serif"],
        mono: ["'Roboto Mono'", "ui-monospace", "monospace"],
      },
      // M3 shape scale
      borderRadius: {
        "md3-xs": "4px",
        "md3-sm": "8px",
        "md3-md": "12px",
        "md3-lg": "16px",
        "md3-xl": "28px",
      },
      // M3 elevation
      boxShadow: {
        "elevation-1": "var(--md-elevation-1)",
        "elevation-2": "var(--md-elevation-2)",
        "elevation-3": "var(--md-elevation-3)",
      },
      // M3 type scale (role = size + line height + tracking; weight via
      // font-medium where the role asks for 500)
      fontSize: {
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "0" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "0" }],
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "0" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.15px" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.5px" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.25px" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.4px" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.5px" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
